# Generated by Django 5.0.1 on 2024-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=255)),
                ('workEmail', models.CharField(max_length=255)),
                ('lineManager', models.CharField(max_length=255)),
                ('request', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='maintenance_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('workEmail', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=5)),
                ('request', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='otherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('workEmail', models.CharField(max_length=255)),
                ('request', models.CharField(max_length=550)),
            ],
        ),
    ]
