# Generated by Django 5.0.1 on 2024-03-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='otherRequest',
            new_name='other_request',
        ),
    ]
