# Generated by Django 5.0.1 on 2024-03-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_otherrequest_other_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance_request',
            old_name='firstName',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='other_request',
            old_name='firstName',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='maintenance_request',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='other_request',
            name='lastName',
        ),
    ]
