from django.db import models

# Create your model

class device_request(models.Model):
    dateCreated = models.DateTimeField(auto_now_add=True)

    fullName = models.CharField(max_length=255)
    workEmail = models.CharField(max_length=255)
    lineManager = models.CharField(max_length=255)
    request = models.CharField(max_length=550)

    def __str__(self):
        return self.fullName #create an autogenerated requestid and return it in future 

class maintenance_request(models.Model):
    dateCreated = models.DateTimeField(auto_now_add=True)

    fullName = models.CharField(max_length=255)
    workEmail = models.CharField(max_length=255)
    building = models.CharField(max_length=5)
    request = models.CharField(max_length=550)


    def __str__(self):
        return self.fullName
    
class other_request(models.Model):
    dateCreated = models.DateTimeField(auto_now_add=True)

    fullName = models.CharField(max_length=255)
    workEmail = models.CharField(max_length=255)
    request = models.CharField(max_length=550) #see if you can add request tags

    def __str__(self):
        return self.fullName